config/routes.rb
Rails.application.routes.draw do
  resources :staffsearches, only: [:new, :create]
  resources :staffs, only: [:new, :create, :index, :edit, :update]
  resources :searchers
  resources :accounts

  root to: 'searchers#new'

end

app/models/staff.rb
class Staff < ActiveRecord::Base
	validates_presence_of :room_number
	validate :validate_time, :on => :update

	def validate_time
		if self.time_in_was
	      #make sure the new time in is after the old
	      if self.time_in
	        if self.time_in.strftime( "%H%M%S%N" ) < self.time_in_was.strftime( "%H%M%S%N" )
	        	errors.add(:staff, 'Time in has to be after the previous time.')
	        end
	      end
	      if self.time_out
	        if self.time_out < self.time_in
	        	errors.add(:staff, 'Time out has to be after time in.')
	        end
	      end
	    else
	      #Make sure new time_in is after time.now
	      if self.time_in
	        if self.time_in.strftime( "%H%M%S%N" ) < Time.now.beginning_of_minute.strftime( "%H%M%S%N" )
	        	errors.add(:staff, 'Time in has to be after the current time.')
	        end
	        if self.time_out
	          if self.time_out < self.time_in
	          	errors.add(:staff, 'Time out has to be after time in.')
	          end
	        end
	      else
	        if self.time_out
	        	errors.add(:staff, 'There must be a time in.')
	        end
	      end
	    end
	end
end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  def new
    @staff = Staff.new
  end

  def create
    @staff = Staff.new(staff_params)
    @staff.housekeeping_date = Date.today
    if @staff.save
      redirect_to staffs_path(date: Date.today), notice: "Housekeeping was successfully created."
    else
      render :new
    end
  end

  def index
    @date_chosen = params[:date]
    @yesterday = params[:date].to_date - 1.day
    @date_chosen_format = params[:date].to_date.strftime('%d %b %Y')
    @yesterday_format = @yesterday.strftime('%d %b %Y')
    @yes_staffs = Staff.where(:housekeeping_date => @yesterday)
    @yes_staffs = @yes_staffs.sort_by {|yes| yes.room_number}
    @to_staffs = Staff.where(:housekeeping_date => @date_chosen)
    @to_staffs = @to_staffs.sort_by {|tos| tos.room_number}
  end

  def edit
    @staff = Staff.find(params[:id])
  end

  def update
    @staff = Staff.find(params[:id])
    @account = Account.find_by(:room_no => @staff.room_number, :account_date => @staff.housekeeping_date)
    if @staff.update(staff_params)
      if @account
        @account.update(:remark => staff_params[:remark])
      end
      redirect_to staffs_path(date: Date.today), notice: "Housekeeping was successfully updated."
    else
      render :edit
    end
  end

  private
  def staff_params
  	params.require(:staff).permit(:housekeeping_date, :room_number, :time_in, :time_out, :name, :remark)
  end

end

app/helpers/staff_helper.rb
module StaffHelper
end

app/views/staffs/_form.html.erb
<div class="page">
<%= form_for @staff do |f| %>
  <% if @staff.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@staff.errors.count, "error") %> prohibited this staff from being saved:</h2>
      <ul>
      <% @staff.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 <div class="staff-form-container">
  <div class="row staff-form">
	<div class="name">
		<%= f.label :name %><br>
		<%= f.text_field :name, :class => "name-field" %>
		<div class="room">
			<%= f.label :room %><br>
			<%= @staff.room_number %>
			<div class="time-in">
				<%= f.label :time_in %><br>
				<%= f.time_select :time_in, ampm: true, include_blank: true, ignore_date: true%>		
				<div class="time-out">
					<%= f.label :time_out %><br>
					<%= f.time_select :time_out, ampm: true, include_blank: true, ignore_date: true %>
				</div>
			</div>
		</div>
	</div>
	<div class="remark">
		<%= f.label :remark %><br>
		<%= f.text_area :remark %>
			<div class="staff-submit-button action">
				<%= f.submit "Create housekeeping" %>
			</div>
	</div>
  </div>
  </div>
<% end %>
</div>

<script type="text/javascript">
	console.log('<%= Time.now.beginning_of_minute%>');
	console.log('<%= @staff.time_in %>');
</script>

app/views/staffs/edit.html.erb
<%= render 'form' %>

app/views/staffs/index.html.erb
<div class="page">
<div class="pull-right add-button"><%= link_to "ADD", new_staff_path %></div>
<h3>Staff work for: <%= @yesterday_format %></h3>
<table class="table table-hover table-bordered">
  <thead>
    <tr>
      <th class="col-md-1 staff-name-col">Name</th>
      <th class="col-md-1 room-no-col">Room no.</th>
      <th class="col-md-1 time-in-col">Time in</th>
      <th class="col-md-1 time-out-col">Time out</th>
      <th class="col-md-8 remark-col">Remark</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @yes_staffs.each do |staff| %>
      <tr>
      	<td class="col-md-1 staff-name-col"><%= staff.name %></td>
        <td class="col-md-1 room-no-col"><%= staff.room_number %></td>
        <% if staff.time_in %>
        <td class="col-md-1 time-in-col"><%= staff.time_in.strftime("%I:%M %p") %></td> 
        <% else %>
        <td class="col-md-1 time-in-col"></td>
        <% end %>
        <% if staff.time_out %>
        <td class="col-md-1 time-out-col"><%= staff.time_out.strftime("%I:%M %p") %></td>
        <% else %>
        <td class="col-md-1 time-out-col"></td>
        <% end %>
        <td class="col-md-8 remark-col"><%= staff.remark %></td>
        <td><%= link_to "Edit", edit_staff_path(id: staff.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h3>Staff work for: <%= @date_chosen_format %></h3>

<table class="table table-hover table-bordered">
  <thead>
    <tr>
      <th class="col-md-1 staff-name-col">Name</th>
      <th class="col-md-1 room-no-col">Room no.</th>
      <th class="col-md-1 time-in-col">Time in</th>
      <th class="col-md-1 time-out-col">Time out</th>
      <th class="col-md-8 remark-col">Remark</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @to_staffs.each do |staff| %>
      <tr>
        <td class="col-md-1 staff-name-col"><%= staff.name %></td>
        <td class="col-md-1 room-no-col"><%= staff.room_number %></td>
        <% if staff.time_in %>
        <td class="col-md-1 time-in-col"><%= staff.time_in.strftime("%I:%M %p") %></td> 
        <% else %>
        <td class="col-md-1 time-in-col"></td>
        <% end %>
        <% if staff.time_out %>
        <td class="col-md-1 time-out-col"><%= staff.time_out.strftime("%I:%M %p") %></td>
        <% else %>
        <td class="col-md-1 time-out-col"></td>
        <% end %>
        <td class="col-md-8 remark-col"><%= staff.remark %></td>
        <td><%= link_to "Edit", edit_staff_path(id: staff.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/staffs/new.html.erb
<div class="page">
<%= form_for @staff do |f| %>
  <% if @staff.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@staff.errors.count, "error") %> prohibited this staff from being saved:</h2>
      <ul>
      <% @staff.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 <div class="staff-form-container">
  <div class="row staff-form">
	<div class="name">
		<%= f.label :name %><br>
		<%= f.text_field :name, :class => "name-field" %>
		<div class="room">
			<%= f.label :room %><br>
			<%= f.number_field :room_number, :id => "room-num-field" %>
			<div class="time-in">
				<%= f.label :time_in %><br>
				<%= f.time_select :time_in, ampm: true, include_blank: true, ignore_date: true%>		
				<div class="time-out">
					<%= f.label :time_out %><br>
					<%= f.time_select :time_out, ampm: true, include_blank: true, ignore_date: true %>
				</div>
			</div>
		</div>
	</div>
	<div class="remark">
		<%= f.label :remark %><br>
		<%= f.text_area :remark %>
			<div class="staff-submit-button action">
				<%= f.submit "Create housekeeping" %>
			</div>
	</div>
  </div>
  </div>
<% end %>
</div>