config/routes.rb
Rails.application.routes.draw do
  resources :staffsearches, only: [:new, :create]
  resources :staffs, only: [:new, :create, :index, :edit, :update]
  resources :searchers
  resources :accounts

  root to: 'searchers#new'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SHaccount</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
	<div class="container">
		<ul class="nav nav-tabs">
			<li class="month-tab"><%= link_to "Months", new_searcher_path %></li>
			<li class="new-tab"><%= link_to "New", new_account_path %></li>
			<li class="day-tab"><%= link_to "Day", accounts_path(today_day: true) %></li>
			<li class="night-tab"><%= link_to "Night", accounts_path(today_night: true) %></li>
			<li class="today-tab pull-right"><%= link_to "Clean room", staffs_path(date: Date.today) %></li>
			<li class="records-tab pull-right"><%= link_to "Records", new_staffsearch_path %></li>
		</ul>
	</div>

	<% if flash[:notice] %>
		<div class="alert alert-success">
			<button type="button" class="close" data-dismiss="alert">&times;</button>
			<%= flash[:notice] %>
		</div>
	<% elsif flash.now[:alert] %>
		<div class="alert alert-danger">
			<button type="button" class="close" data-dismiss="alert">&times;</button>
			<%= flash.now[:alert] %>
		</div>
	<% elsif flash[:alert] %>
		<div class="alert alert-warning">
			<button type="button" class="close" data-dismiss-"alert">&times;</button>
			<%= flash[:alert] %>
		</div>
	<% end %>
<%= yield %>

</body>
</html>