config/routes.rb
Rails.application.routes.draw do
  resources :staffsearches, only: [:new, :create]
  resources :staffs, only: [:new, :create, :index, :edit, :update]
  resources :searchers
  resources :accounts

  root to: 'searchers#new'

end

app/models/account.rb
class Account < ActiveRecord::Base
	has_one :account_searcher

	validates_presence_of :room_no
	validates_presence_of :days
	validates_presence_of :price
	validates_presence_of :deposit
	if !:day
		validates_presence_of :night
	end
	if !:night
		validates_presence_of :day
	end
		
	validate :check_rm_cleaned, :on => [:create, :update]

    private 

    def check_rm_cleaned
    	@yesterdays_accounts = Account.where(:account_date => Time.now.yesterday)
	    @todays_accounts = Account.where(:account_date => Time.now)
	    @total_accounts = []
	    @total_accounts = @yesterdays_accounts + @todays_accounts
	    @total_room_numbers = []
	    @total_accounts.each do |account|
	      @total_room_numbers << account.room_no
	    end
	    @yesterdays_housekeeping = Staff.where("DATE(created_at) = ?", Date.today - 1).where.not(:time_out => nil)
	    @todays_housekeeping = Staff.where("DATE(created_at) = ?", Date.today).where.not(:time_out => nil)
	    @total_housekeeping = []
	    @total_housekeeping = @yesterdays_housekeeping + @todays_housekeeping
	    @total_housekeeping.each do |cleaned|
	      @total_room_numbers.each_with_index do |room, index|
	        if (room == cleaned.room_number)
	          @total_room_numbers.delete_at(index)
	          break
	        end
	      end
	    end

    	@total_room_numbers.each do |uncleaned_rms|
	      	if self.room_no == uncleaned_rms 
	      		if self.old_room != nil
		      		if self.room_no != self.old_room
			        	errors.add(:account, 'Room not cleaned.')
			       		break
			       	end
			    else
			    	errors.add(:account, 'Room not cleaned.')
			       	break
			    end
	      	end
    	end
	end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def index
    @search_from = params[:search_from]
    @search_to = params[:search_to]
    @accounts = []

    @day_total_price = 0
    @day_total_deposit = 0
    @day_total_misc = 0
    @day_total_gst = 0
    @day_total_cc = 0
    @day_total_hr = 0
    @day_total_hr_cc = 0
    @day_total = 0

    @night_total_price = 0
    @night_total_deposit = 0
    @night_total_misc = 0
    @night_total_gst = 0
    @night_total_cc = 0
    @night_total_hr = 0
    @night_total_hr_cc = 0
    @night_total = 0

    @total_price = 0
    @total_deposit = 0
    @total_misc = 0
    @total_gst = 0
    @total_cc = 0
    @total_hr = 0
    @total_hr_cc = 0
    @total = 0

    if params[:today_day]
      @day_accounts = Account.where(:day => true, :account_date => Date.today)
      @day_accounts = @day_accounts.sort_by {|acc| acc.invoice_no}
      @day_accounts.each do |account|
        @day_total_price += account.price
        @day_total_gst += ((account.price/1.06)* 0.06)
        @day_total_deposit += account.deposit
        @day_total_misc += account.miscellaneous || 0
        @day_total_cc += account.cc || 0
        @day_total_hr += account.hr_use || 0
        @day_total_hr_cc += account.hr_cc || 0
      end
      @day_total = @day_total_price + @day_total_misc + @day_total_hr
      render :day
    end

    if params[:today_night]
      day_start = Time.parse "08:00 am"
      night_start = Time.parse "08:00 pm"
      midnight = Time.now.beginning_of_day
      end_of_the_day = Time.now.end_of_day
      #if next day already
      if midnight < Time.now && Time.now < day_start 
        @night_accounts = Account.where(:night => true, :account_date => Time.now.yesterday)         
      else
        @night_accounts = Account.where(:night => true, :account_date => Date.today)
      end
      @night_accounts = @night_accounts.sort_by {|acc| acc.invoice_no}
      @night_accounts.each do |account|
        @night_total_price += account.price
        @night_total_gst += ((account.price/1.06)* 0.06)
        @night_total_deposit += account.deposit
        @night_total_misc += account.miscellaneous || 0
        @night_total_cc += account.cc || 0
        @night_total_hr += account.hr_use || 0
        @night_total_hr_cc += account.hr_cc || 0
      end
      @night_total = @night_total_price + @night_total_misc + @night_total_hr
      render :night
    end

  	if(@search_from && @search_to)
  		@accounts = Account.where(:account_date => @search_from.to_time..@search_to.to_time)
      @day_accounts = @accounts.where(:day => true)
      @day_accounts = @day_accounts.sort_by {|acc| acc.invoice_no}
      @night_accounts = @accounts.where(:night => true)
      @night_accounts = @night_accounts.sort_by {|acc| acc.invoice_no}
  		@accounts.each do |account|
        if account.day
          @day_total_price += account.price
          @day_total_gst += ((account.price/1.06)* 0.06)
          @day_total_deposit += account.deposit
          @day_total_misc += account.miscellaneous || 0
          @day_total_cc += account.cc || 0
          @day_total_hr += account.hr_use || 0
          @day_total_hr_cc += account.hr_cc || 0
        elsif account.night
          @night_total_price += account.price
          @night_total_gst += ((account.price/1.06)* 0.06)
          @night_total_deposit += account.deposit
          @night_total_misc += account.miscellaneous || 0
          @night_total_cc += account.cc || 0
          @night_total_hr += account.hr_use || 0
          @night_total_hr_cc += account.hr_cc || 0
        end
  			@total_price += account.price
        @total_gst += ((account.price/1.06)* 0.06)
  			@total_deposit += account.deposit
        @total_misc += account.miscellaneous || 0
        @total_cc += account.cc || 0
        @total_hr += account.hr_use || 0
        @total_hr_cc += account.hr_cc || 0
  		end
      @day_total = @day_total_price + @day_total_misc + @day_total_hr
      @night_total = @night_total_price + @night_total_misc + @night_total_hr
      @total = @total_price + @total_misc + @total_hr
  	end
  end

  def show
  	@account = Account.find(params[:id])
  end

  def new
  	@account = Account.new
    @housekeeping = Staff.new
  end

  def create 
  	@account = Account.new(account_params)
    @account.old_room = nil

    day_start = Time.parse "08:00 am"
    night_start = Time.parse "08:00 pm"
    midnight = Time.now.beginning_of_day
    end_of_the_day = Time.now.end_of_day
    beginning_of_month = Time.now.beginning_of_month + 8.hours
    beginning_of_last_month = beginning_of_month - 1.month
    now = Time.now

    #if night shift
    if midnight < Time.now && Time.now < day_start 
      @account.account_date = Time.now.yesterday
      @account.night = true
    elsif night_start < Time.now && Time.now < end_of_the_day
      @account.account_date = Date.today
      @account.night = true
    else
      @account.account_date = Date.today
      @account.day = true
    end

    current_accounts = []
    #If same month
    if (now.month == beginning_of_month.month)
      #If new invoice month (reset invoice no to 1 for new)
      if (now > beginning_of_month)
        current_accounts = Account.where(:account_date => beginning_of_month..now)
      else #Use old invoice number++ (still on previous month)
        current_accounts = Account.where(:account_date => beginning_of_last_month..beginning_of_month)
      end
    end
    if current_accounts.length > 0
      @account.invoice_no = Account.last.invoice_no + 1
    else
      @account.invoice_no = 1
    end

    #Create housekeeping for each day
    @housekeepings = []
    if @account.days
      @account.days.times do |d|
        @housekeeping = Staff.new
        @housekeeping.room_number = @account.room_no
        @housekeeping.housekeeping_date = (Date.today + d.day)
        @housekeepings << @housekeeping
      end

      if @account.remark
        @housekeepings[0].remark = @account.remark
      end
    end

    if @account.save
      @housekeepings.each do |hs|
        hs.save!
      end
      redirect_to @account, notice: 'Account was successfully created.'
    else
      render :new
    end
  end

  def edit
  	@account = Account.find(params[:id])
  end

  def update 
    @account = Account.find(params[:id])
    @account.old_room = @account.room_no
    @housekeepings = []
    @account.days.times do |d|
      @housekeeping = Staff.find_by(:room_number => @account.room_no, :housekeeping_date => (@account.account_date + d.day))
      @housekeepings << @housekeeping
    end 
  	if @account.update(account_params)
      @housekeepings.each do |hk|
        hk.update(:room_number => account_params[:room_no], :remark => account_params[:remark])
      end
  		redirect_to @account, notice: "Account was successfully updated."
  	else
  		render :edit
  	end
  end

  private 
  def account_params
  	params.require(:account).permit(:days, :hr_use, :hr_cc, :old_room, :cc, :day, :night, :account_date, :search_from, :search_to, :invoice_no, :room_no, :price, :extension, :deposit, :miscellaneous, :remark, :date)
  end
end

app/views/accounts/_form.html.erb
<%= form_for @account do |f| %>
  <div class="account-form-container">
    <div class="row">
      <div class="room-field">
      <%= f.label :room %><br>
      <%= f.number_field :room_no, :id => "input-no" %>
        <div class="days-field">
        <%= f.label :days %><br>
        <%= f.number_field :days, :id => "input-no" %>
          <div class="price-field">
          <%= f.label :Price %><br>
          <%= f.number_field :price, :id => "input-no" %>
            <div class="cc-field">
            <%= f.label :C %><b>C</b><br>
            <%= f.number_field :cc, :id => "input-no" %>
              <div class="hr-field">
              <%= f.label :Hr_Use %><br>
              <%= f.number_field :hr_use, :id => "input-no" %>
                <div class="hr-cc-field">
                <%= f.label :Hr %><b>CC</b><br>
                <%= f.number_field :hr_cc, :id => "input-no" %>
                  <div class="ext-field">
                  <%= f.label :ext %><br>
                  <%= f.number_field :extension, :id => "input-no" %>
                    <div class="dep-field">
                    <%= f.label :dep %><br>
                    <%= f.number_field :deposit, :id => "input-no" %>
                      <div class="misc-field">
                      <%= f.label :misc %>.<br>
                      <%= f.number_field :miscellaneous, :id => "input-no" %>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="account-remark">
      <%= f.label :Remark %><br>
      <%= f.text_area :remark %>
        <div class="submit-button actions">
          <%= f.submit "Create Account" %>
        </div>
    </div>
    <% if @account.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>
        <ul>
        <% @account.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  </div>
 <% end %>

<script type="text/javascript">
 var dp1 = $('#dp1').datepicker({
    todayHighlight: true,
    format: 'dd M yyyy'
  }).on('changeDate', function(ev) {
    dp1.hide();
  }).data('datepicker');
</script>
 

app/views/accounts/day.html.erb
<div class="page">
<table class="table table-hover table-bordered">
  <thead>
    <tr>
      <th class="date-col">Date</th>
      <th class="time-created-col">Time</th>
      <th class="invoice-no-col">Invoice</th>
      <th class="room-no-col">Room</th>
      <th class="day-price-col">Day</th>
      <th class="cc-col">CC</th>
      <th class="gst-col">GST</th>
      <th class="hr-col">Hr Use</th>
      <th class="hr-cc-head-col">Hr CC</th>
      <th class="extension-col">Ext.</th>
      <th class="deposit-col">Deposit</th>
      <th class="misc-col">Misc</th>
      <th class="remark-col">Remark</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @day_accounts.each do |account| %>
        <tr>
        	<td class="date-col"><%= account.account_date.strftime('%d %b %Y') %></td>
          <td class="time-created-col"><%= account.created_at.to_time.strftime("%R") %></td>
          <td class="invoice-no-col"><%= account.invoice_no %></td>
          <td class="room-no-col"><%= account.room_no %></td> 
          <td class="day-price-col"><%= account.price %></td>
          <td class="cc-col"><%= account.cc %></td>
          <% if account.price %>
          <td class="gst-col"><%= ((account.price/1.06)* 0.06).round(2) %></td>
          <% else %>
          <td class="gst-col">0</td>
          <% end %>
          <td class="hr-col"><%= account.hr_use %></td>
          <td class="hr-cc-col"><%= account.hr_cc %></td>
          <td class="extension-col"><%= account.extension %></td>
          <td class="deposit-col"><%= account.deposit %></td>
          <td class="misc-col"><%= account.miscellaneous %></td>
          <td class="remark-col"><%= account.remark %></td>
          <td><%= link_to "Edit", edit_account_path(id: account.id) %></td>
        </tr>
    <% end %>
    <tr>
    	<td class="total total-title">Totals</td>
      <td class="total time-created-col"></td>
    	<td class="total invoice-no-col"></td>
    	<td class="total room-no-col"><%= @day_accounts.length %></td>
    	<td class="total total-day-price"><%= @day_total_price || 0 %></td>
      <td class="total cc-col"><%= @day_total_cc %></td>
      <% if @day_total_gst %>
      <td class="total gst-col"><%= @day_total_gst.round(2) %></td>
      <% else %>
      <td class="total gst-col">0</td>
      <% end %>
      <td class="total total-hr-col"><%= @day_total_hr || 0 %></td>
      <td class="total hr-cc-col"><%= @day_total_hr_cc || 0 %></td>
      <td class="total extension-col"></td>
    	<td class="total deposit-col"><%= @day_total_deposit || 0 %></td>
      <td class="total total-misc-col"><%= @day_total_misc || 0 %></td>
      <td class="total total-title-col"></td>
      <td class="total total-price-col"><%= @day_total %></td>
    </tr>
  </tbody>
</table>
</div>

app/views/accounts/edit.html.erb
<div class="page">
<h1>Edit account</h1>

<%= render 'form' %>
</div>

app/views/accounts/index.html.erb
<div class="page">
<h2>Accounts for: <%= @search_from.to_date.strftime('%d %b %Y') %> - <%= @search_to.to_date.strftime('%d %b %Y') %></h2>
<table class="table table-hover table-bordered">
  <thead>
    <tr>
      <th class="date-col">Date</th>
      <th class="time-created-col">Time</th>
      <th class="invoice-no-col">Invoice</th>
      <th class="room-no-col">Room</th>
      <th class="day-price-col">Day</th>
      <th class="gst-col">GST</th>
      <th class="cc-col">CC</th>
      <th class="hr-col">Hr Use</th>
      <th class="hr-cc-head-col">Hr CC</th>
      <th class="extension-col">Ext.</th>
      <th class="deposit-col">Deposit</th>
      <th class="misc-col">Misc</th>
      <th class="remark-col">Remark</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @day_accounts.each do |account| %>
        <tr>
        	<td class="date-col"><%= account.account_date.strftime('%d %b %Y') %></td>
          <td class="time-created-col"><%= account.created_at.to_time.strftime("%R") %></td>
          <td class="invoice-no-col"><%= account.invoice_no %></td>
          <td class="room-no-col"><%= account.room_no %></td> 
          <td class="day-price-col"><%= account.price %></td>
          <% if account.price %>
          <td class="gst-col"><%= ((account.price/1.06)* 0.06).round(2) %></td>
          <% else %>
          <td class="gst-col">0</td>
          <% end %>
          <td class="cc-col"><%= account.cc %></td>
          <td class="hr-col"><%= account.hr_use %></td>
          <td class="hr-cc-col"><%= account.hr_cc %></td>
          <td class="extension-col"><%= account.extension %></td>
          <td class="deposit-col"><%= account.deposit %></td>
          <td class="misc-col"><%= account.miscellaneous %></td>
          <td class="remark-col"><%= account.remark %></td>
          <td><%= link_to "Edit", edit_account_path(id: account.id) %></td>
        </tr>
    <% end %>
    <tr>
    	<td class="total total-title">Totals</td>
      <td class="total time-created-col"></td>
    	<td class="total invoice-no-col"></td>
    	<td class="total room-no-col"><%= @day_accounts.length %></td>
    	<td class="total total-day-price"><%= @day_total_price || 0 %></td>
      <% if @day_total_gst %>
      <td class="total gst-col"><%= @day_total_gst.round(2) %></td>
      <% else %>
      <td class="total gst-col">0</td>
      <% end %>
      <td class="total cc-col"><%= @day_total_cc %></td>
      <td class="total total-hr-col"><%= @day_total_hr || 0 %></td>
      <td class="total hr-cc-col"><%= @day_total_hr_cc || 0 %></td>
      <td class="total extension-col"></td>
    	<td class="total deposit-col"><%= @day_total_deposit || 0 %></td>
      <td class="total total-misc-col"><%= @day_total_misc || 0 %></td>
      <td class="total total-title-col"></td>
      <td class="total total-price-col"><%= @day_total %></td>
    </tr>
  </tbody>
</table>

<table class="table table-hover table-bordered">
  <thead>
    <tr>
      <th class="date-col">Date</th>
      <th class="time-created-col">Time</th>
      <th class="invoice-no-col">Invoice</th>
      <th class="room-no-col">Room</th>
      <th class="night-price-col">Night</th>
      <th class="gst-col">GST</th>
      <th class="cc-col">CC</th>
      <th class="hr-col">Hr Use</th>
      <th class="hr-cc-head-col">Hr CC</th>
      <th class="extension-col">Ext.</th>
      <th class="deposit-col">Deposit</th>
      <th class="misc-col">Misc</th>
      <th class="remark-col">Remark</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @night_accounts.each do |account| %>
        <tr>
          <td class="date-col"><%= account.account_date.strftime('%d %b %Y') %></td>
          <td class="time-created-col"><%= account.created_at.to_time.strftime("%R") %></td>
          <td class="invoice-no-col"><%= account.invoice_no %></td>
          <td class="room-no-col"><%= account.room_no %></td> 
          <td class="night-price-col"><%= account.price %></td>
          <% if account.price %>
          <td class="gst-col"><%= ((account.price/1.06)* 0.06).round(2)%></td>
          <% else %>
          <td class="gst-col">0</td>
          <% end %>
          <td class="cc-col"><%= account.cc %></td>
          <td class="hr-col"><%= account.hr_use %></td>
          <td class="hr-cc-col"><%= account.hr_cc %></td>
          <td class="extension-col"><%= account.extension %></td>
          <td class="deposit-col"><%= account.deposit %></td>
          <td class="misc-col"><%= account.miscellaneous %></td>
          <td class="remark-col"><%= account.remark %></td>
          <td><%= link_to "Edit", edit_account_path(id: account.id) %></td>
        </tr>
    <% end %>
    <tr>
      <td class="total total-title">Totals</td>
      <td class="total time-created-col"></td>
      <td class="total invoice-no-col"></td>
      <td class="total room-no-col"><%= @night_accounts.length %></td>
      <td class="total total-night-price"><%= @night_total_price || 0 %></td>
      <% if @night_total_gst %>
      <td class="total gst-col"><%= @night_total_gst.round(2) %></td>
      <% else %>
      <td class="total gst-col">0</td>
      <% end %>
      <td class="total cc-col"><%= @night_total_cc %></td>
      <td class="total total-hr-col"><%= @night_total_hr %></td>
      <td class="total hr-cc-col"><%= @night_total_hr_cc %></td>
      <td class="total extension-col"></td>
      <td class="total deposit-col"><%= @night_total_deposit || 0 %></td>
      <td class="total total-misc-col"><%= @night_total_misc || 0 %></td>
      <td class="total total-title-col"></td>
      <td class="total total-price-col"><%= @night_total %></td>
    </tr>
  </tbody>
</table>

<!-- Total table  -->
<table class="table table-bordered">
  <thead>
    <tr>
      <th class="total total-title">Total</th>
      <th class="total room-no-col">Rooms</th>
      <th class="total price-col">Night & Day</th>
      <th class="total gst-col">GST</th>
      <th class="total cc-col">CC</th>
      <th class="total gst-col">CC GST</th>
      <th class="total hr-col">Hr Use</th>
      <th class="total gst-col">Hr GST</th>
      <th class="total hr-cc-head-col">Hr CC</th>
      <th class="total gst-col">Hr CC GST</th>
      <th class="total deposit-col">Deposit</th>
      <th class="total misc-col">Miscellaneous</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td class="total total-price-col"><%= @total %></td>
      <td class="total room-no-col"><%= @accounts.length %></td>
      <td class="total total-price"><%= @total_price %></td>
      <% if @total_gst %>
        <td class="total gst-col"><%= @total_gst.round(2) %></td>
      <% else %>
        <td class="total gst-col">0</td>
      <% end %>
      <td class="total cc-col"><%= @total_cc %></td>
      <% if @total_cc %>
        <td class="total gst-col"><%= ((@total_cc/1.06)* 0.06).round(2) %></td>
      <% else %>
        <td class="total gst-col">0</td>
      <% end %>
      <td class="total total-hr-col"><%= @total_hr %></td>
      <% if @total_hr %>
        <td class="total gst-col"><%= ((@total_hr/1.06)* 0.06).round(2) %></td>
      <% else %>
        <td class="total gst-col">0</td>
      <% end %>
      <td class="total hr-cc-col"><%= @total_hr_cc %></td>
      <% if @total_hr_cc %>
        <td class="total gst-col"><%= ((@total_hr_cc/1.06)* 0.06).round(2) %></td>
      <% else %>
        <td class="total gst-col">0</td>
      <% end %>
      <td class="total deposit-col"><%= @total_deposit %></td>
      <td class="total total-misc-col"><%= @total_misc %></td>
    </tr>
  </tbody>
</table>
</div>

app/views/accounts/new.html.erb
<div class="page">
<h1>New account</h1>

<%= render 'form' %>
</div>

app/views/accounts/night.html.erb
<div class="page">
<table class="table table-hover table-bordered">
  <thead>
    <tr>
      <th class="date-col">Date</th>
      <th class="time-created-col">Time</th>
      <th class="invoice-no-col">Invoice</th>
      <th class="room-no-col">Room</th>
      <th class="night-price-col">Night</th>
      <th class="cc-col">CC</th>
      <th class="gst-col">GST</th>
      <th class="hr-col">Hr Use</th>
      <th class="hr-cc-head-col">Hr CC</th>
      <th class="extension-col">Ext.</th>
      <th class="deposit-col">Deposit</th>
      <th class="misc-col">Misc</th>
      <th class="remark-col">Remark</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @night_accounts.each do |account| %>
        <tr>
          <td class="date-col"><%= account.account_date.strftime('%d %b %Y') %></td>
          <td class="time-created-col"><%= account.created_at.to_time.strftime("%R") %></td>
          <td class="invoice-no-col"><%= account.invoice_no %></td>
          <td class="room-no-col"><%= account.room_no %></td> 
          <td class="night-price-col"><%= account.price %></td>
          <td class="cc-col"><%= account.cc %></td>
          <% if account.price %>
          <td class="gst-col"><%= ((account.price/1.06)* 0.06).round(2) %></td>
          <% else %>
          <td class="gst-col">0</td>
          <% end %>
          <td class="hr-col"><%= account.hr_use %></td>
          <td class="hr-cc-col"><%= account.hr_cc %></td>
          <td class="extension-col"><%= account.extension %></td>
          <td class="deposit-col"><%= account.deposit %></td>
          <td class="misc-col"><%= account.miscellaneous %></td>
          <td class="remark-col"><%= account.remark %></td>
          <td><%= link_to "Edit", edit_account_path(id: account.id) %></td>
        </tr>
    <% end %>
    <tr>
      <td class="total total-title">Totals</td>
      <td class="total time-created-col"></td>
      <td class="total invoice-no-col"></td>
      <td class="total room-no-col"><%= @night_accounts.length %></td>
      <td class="total total-night-price"><%= @night_total_price || 0 %></td>
      <td class="total cc-col"><%= @night_total_cc %></td>
      <% if @night_total_gst %>
      <td class="total gst-col"><%= @night_total_gst.round(2) %></td>
      <% else %>
      <td class="total gst-col">0</td>
      <% end %>
      <td class="total total-hr-col"><%= @night_total_hr || 0 %></td>
      <td class="total hr-cc-col"><%= @night_total_hr_cc || 0 %></td>
      <td class="total extension-col"></td>
      <td class="total deposit-col"><%= @night_total_deposit || 0 %></td>
      <td class="total total-misc-col"><%= @night_total_misc || 0 %></td>
      <td class="total total-title-col"></td>
      <td class="total total-price-col"><%= @night_total %></td>
    </tr>
  </tbody>
</table>
</div>

app/views/accounts/show.html.erb
<div class="page">
<strong>Account</strong><br>
<table class="table table-hover table-bordered">
  <thead>
    <tr>
      <th class="date-col">Date</th>
      <th class="room-no-col">Room</th>
      <th class="days-col">Days</th>
      <th class="price-col">Price</th>
      <th class="cc-col">CC</th>
      <th class="hr-col">Hr Use</th>
      <th class="hr-cc-col">Hr CC</th>
      <th class="extension-col">Ext.</th>
      <th class="deposit-col">Deposit</th>
      <th class="misc-col">Misc</th>
      <th class="remark-col">Remark</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
  	<tr>
	<td><%= @account.account_date.strftime('%d %b %Y') %></td>
	<td><%= @account.room_no %></td>
  <td><%= @account.days %></td>
	<td class="price-col"><%= @account.price %></td>
  <td class="cc-col"><%= @account.cc %></td>
  <td class="hr-col"><%= @account.hr_use %></td>
  <td class="hr-cc-col"><%= @account.hr_cc %></td>
	<td class="extension-col"><%= @account.extension %></td>
	<td class="deposit-col"><%= @account.deposit %></td>
	<td><%= @account.miscellaneous %></td>
	<td><%= @account.remark %></td>
  <td><%= link_to "Edit", edit_account_path(id: @account.id) %></td>
	</tr>
  </tbody>
</table>

</div>